spring:
    mvc:
        servlet:
            path: /api
    docker:
        compose:
            enabled: false

    session:
        timeout: 30m
        jdbc:
            initialize-schema: always
            table-name: SPRING_SESSION
            schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 50
            minimum-idle: 20
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000
            auto-commit: false

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml

server:
    tomcat:
        threads:
            max: 200
            min-spare: 50
    port: 8082

lock:
    timeout: 1200

retry:
    delay: 600
    multiplier: 1.2
    max_attempts: 5