name: Wallet Service CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Set execute permission
                run: chmod +x gradlew
            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
            -   name: Build with Gradle Wrapper
                run: ./gradlew assemble
            -   name: Check code style with Spotless
                run: ./gradlew spotlessCheck
            -   name: Auto-format code
                run: ./gradlew spotlessApply

    test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set execute permission for gradlew  # ← ДОБАВЬТЕ И ЗДЕСЬ
              run: chmod +x gradlew
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
            - name: Run tests with Gradle Wrapper
              run: ./gradlew test

    dependency-submission:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
            -   name: Generate and submit dependency graph
                uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582
